learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name="logout"),

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional informations
    portofolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

learning_users/basic_app/forms.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portofolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',context = {'registered':registered,'user_form':user_form,'profile_form':profile_form})


def user_login(request):

    if request.method == 'POST':
        logged_username = request.POST.get('username')
        logged_password = request.POST.get('password')

        user = authenticate(username=logged_username,password=logged_password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print(f"{logged_username} tried to log in and failed")
            return HttpResponse("invalid login details supplied")

    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">Hello User!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'index'%}">DJANGO HOME<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'admin:index'%}">Admin<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'basic_app:register'%}">Register<span class="sr-only">(current)</span></a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'logout'%}"><button class="btn btn-primary" type="button" name="button">Logout</button></a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'basic_app:login'%}"><button class="btn btn-primary" type="button" name="button">Login</button></a>
         </li>
        {%endif%}
        </ul>
    </div>
  </nav>
  <br>
  <br>
  <br>
  <br>
  <div class="container">
  {%block body_block%}
  {%endblock%}
  </div>

  </body>
</html>

learning_users/templates/basic_app/index.html
{%extends 'basic_app/base.html'%}
{%block body_block%}
<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>
{%endblock%}

learning_users/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}
{%block body_block%}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{%url 'basic_app:login'%}" method="post">
    {%csrf_token%}

    <label for="username">Username: </label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="password">

    <input type="submit" name="" value="Login">
  </form>
</div>


{%endblock%}

learning_users/templates/basic_app/registration.html
{%extends 'basic_app/base.html'%}
{%block body_block%}

<div class="jumbotron">
  {%if registered%}
    <h1>Thank you for registering!</h1>
  {%else%}
    <h1>Register Here!</h1>
    <h3>Fill out the form: </h3>

    <form enctype="multipart/form-data" method="post">
      {%csrf_token%}
      {{user_form}}
      {{profile_form}}
      <input type="submit" name="" value="Register!">
  </div>
    </form>
  {%endif%}
</div>

{%endblock%}